# -*- compile-command: "docker-compose down; docker rmi kafkadocker_kafka -f && docker-compose up --force-recreate -d" -*-
# docker-compose down; docker rm $(docker ps -a -f status=exited -q); docker rmi $(docker images -f dangling=true -q); docker images; docker ps -a
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
      - "22"
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
